import React from 'react';
import { useLocation, Link } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { ItemMaster } from '../types';
import { useDatabase } from '../hooks/useDatabase';
import { useSettings } from '../hooks/useSettings';
import PrintLayout from '../components/ui/PrintLayout';
import { Spinner } from '../components/ui/Spinner';

const PrintItemMasterPage: React.FC = () => {
    const location = useLocation();
    const { settings } = useSettings();
    const { items, filterCriteria, generatedDate, stockCounts } = location.state || {};
    const { data, loading } = useDatabase();
    const { categories } = data;

    if (loading) {
        return <div className="flex items-center justify-center min-h-screen"><Spinner size="lg" /></div>;
    }

    if (!items) {
        return (
            <PrintLayout title="Error: Report Data Not Found">
                <div className="flex flex-col items-center justify-center text-center">
                    <h1 className="text-2xl font-bold text-red-600">Error: Report Data Not Found</h1>
                    <p className="mt-2 text-secondary-600">This page may have been accessed directly. Please generate a report from the Item Management page first.</p>
                    <Link to="/items">
                        <Button className="mt-6">Go to Item Management</Button>
                    </Link>
                </div>
            </PrintLayout>
        );
    }
    
    const ReportHeader = () => (
        <div className="text-center mb-8 pb-4 border-b-2 border-gray-800">
            <h1 className="text-3xl font-bold text-gray-800">{settings.appName}</h1>
            <h2 className="text-2xl font-semibold text-gray-700 mt-1">Item Master List Report</h2>
            <div className="mt-2 text-sm text-gray-500">
                <p><strong>Filters Applied:</strong></p>
                <p>
                    Search Term: "{filterCriteria.searchTerm || 'None'}" | 
                    Category: {filterCriteria.category} | 
                    Item Type: {filterCriteria.itemType}
                </p>
                <p><strong>Date Generated:</strong> {new Date(generatedDate).toLocaleString()}</p>
            </div>
        </div>
    );

    const StandardTable: React.FC<{headers: string[], children: React.ReactNode}> = ({ headers, children }) => (
        <table className="min-w-full text-sm border-collapse">
            <thead className="bg-gray-100">
                <tr>
                    {headers.map(h => <th key={h} className="p-2 border text-left text-xs font-bold uppercase text-gray-600">{h}</th>)}
                </tr>
            </thead>
            <tbody>{children}</tbody>
        </table>
    );
    
    const getCategoryName = (id: string) => categories.find(c => c.id === id)?.name || 'N/A';
    
    return (
        <PrintLayout title={`Item Master Report - ${new Date(generatedDate).toLocaleDateString()}`}>
            <ReportHeader />
            <section className="mb-8 break-inside-avoid">
                <StandardTable headers={["Item Name", "Brand", "Barcode", "Item Type", "Category", "Stock Count", "Unit"]}>
                   {items.map((item: ItemMaster) => {
                       const stockCount = stockCounts[item.id] || 0;
                       return (
                        <tr key={item.id} className="border-t">
                            <td className="p-2 border font-medium">{item.name}</td>
                            <td className="p-2 border">{item.brand || 'N/A'}</td>
                            <td className="p-2 border font-mono">{item.barcode || 'N/A'}</td>
                            <td className="p-2 border">{item.itemType}</td>
                            <td className="p-2 border">{getCategoryName(item.categoryId)}</td>
                            <td className="p-2 border text-right">{stockCount.toLocaleString()}</td>
                            <td className="p-2 border">{item.unit}</td>
                        </tr>
                       );
                   })}
                </StandardTable>
                {items.length === 0 && <p className="text-gray-600 text-sm p-2">No items match the selected criteria.</p>}
            </section>

             <div className="mt-16 pt-8 border-t-2 border-gray-300 border-dashed grid grid-cols-2 gap-12 text-center text-sm">
                <div>
                    <div className="border-t border-gray-400 mt-8 pt-2 text-gray-600">Generated By (Name & Signature)</div>
                </div>
                <div>
                    <div className="border-t border-gray-400 mt-8 pt-2 text-gray-600">Reviewed By (Name & Signature)</div>
                </div>
            </div>
        </PrintLayout>
    );
};

export default PrintItemMasterPage;